# Assignment 5
This assignment relies heavily on the content covered in the week 5 notes.  Many of the operations you are asked to do here resemble those we went over in class.  Please make sure to reference lesson 5.1 and especially lesson 5.2 notes to guide you through these exercises.  You will need to examine the page:  https://www.marketwatch.com/investing/stock/aapl to understand the structure (tags, classes).  Note that for the sake of consistency, we will use a static version of the marketwatch page, the url for which is: https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl

#### Documentation
[requests library](http://docs.python-requests.org/en/master/)  
[beautifulsoup library](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)  

This assignment will rely on the following libraries.  You will need to import them again as part of your functions. 

In [ ]:
#Packages
#Web scraping packages
from bs4 import BeautifulSoup
import requests

### Problem 1
This problem is all about web-scraping with requests and BeautifulSoup. Parts a - e are missing a few steps. Take some time to fill in the blanks and understand the operations. Part f is left for you to complete and will ask you to combine the operations in parts a - e into one cohesive function.  

a.  Run a get request to url="https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl".  If the status code is not 200, print "request not successful".

In [ ]:
url="https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl"
response=requests.---(url)
if not response.---- == 200:
    print("request not successful")
else:
    print(url)

https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl


**Expected Output**    
https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl

b.  Referencing the above response, create BeautifulSoup object called "results_page" parsed with 'html.parser'.

In [ ]:
# build the BeautifulSoup object and name it results_page
results_page = -----(response.----,'html.parser')
print(type(response))    

<class 'requests.models.Response'>


**Expected Output**       
<class 'requests.models.Response'>

c.  On the webpage:  https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/aapl, look for the section called "Key Data".
![key_data](https://drive.google.com/uc?id=1ZMDc-Q000J5fksE28mMfyIJbFQHvlLUe)

 Inspect the page and verify that the tag/class combination that uniquely identifies each of the items in this table is 'li'/'kv__item'.  Find all elements identified by a tag of 'li' and a class_='kv__item'.  PLEASE NOTE THE **TWO** UNDERSCORES in kv__item. 

In [ ]:
# find all elements with the tag "li" and class_="kv__item"
key_data = results_page.----('li',class_="kv__item")
# print the data type for the kv_data object
print(type(key_data))

<class 'bs4.element.ResultSet'>


**Expected Output**   
<class 'bs4.element.ResultSet'>

d. The code to answer the above question should have returned a list.  Print the first item in this list.  You should get:
```
<li class="kv__item">
<small class="label">Open</small>
<span class="primary ">$144.03</span>
<span class="secondary no-value"></span>
</li>
```

In [ ]:
# print the first element in "key_data"
print(key_data[0])

<li class="kv__item">
<small class="label">Open</small>
<span class="primary ">$144.03</span>
<span class="secondary no-value"></span>
</li>


**Expected Output**   
```
<li class="kv__item">
<small class="label">Open</small>
<span class="primary ">$144.03</span>
<span class="secondary no-value"></span>
</li>
```

Extract the label "Open" and the value "$144.03"

![open_price](https://drive.google.com/uc?id=1OLQ3lVUd84dVytXft1K1GPffcb-ejbxq)

Note:  values may differ.

In [ ]:
label=key_data[0].----(----, class_="label").get_text()
primary_val=key_data[0].find('span',class_=----).----()
print(label)
print(primary_val)

Open
$144.03


**Expected Output**
```
Open
$144.03
```

e.  We need to be able to extract the text for each of the items in the key_data object.  Write a for loop to extract the label and primary value creating a list of the form [(label, value), (label,value),...]

In [ ]:
kd_list=[]
for kv_item in key_data:
    label=kv_item.find('small', class_=----).----()
    value=kv_item.----(----,class_="primary").get_text()
    kd_list.----((label,value))
print(kd_list)

[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]


**Expected Output**
```
[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]
```

f.  Combine all of the above into a function that accepts a stock symbol as an argument and returns the list of (label, value) pairs in the form 
```
[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]
```.  

In [ ]:
def get_key_data(symbol):
    # import the necessary libraries
    import requests
    from bs4 import BeautifulSoup
    url = "https://web.archive.org/web/20211009000648/https://www.marketwatch.com/investing/stock/"+ symbol
    response = ----.----(----)
    if not ----.----==----:
        return None
    kd_list=[]
    try:
        results_page=----(----.----, 'html.parser')
        key_data = results_page.----(----,class_=----)
        for kv_item in key_data:
            label=----.----(----, ----=----).----()
            value=----.----(----, ----=----).----()
            kd_list.----((----,----))
        return kd_list
    except:
        return None
            

Run the function

In [ ]:
results_a = get_key_data("aapl")

[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]


Expected Output
```
[('Open', '$144.03'), ('Day Range', '142.56 - 144.18'), ('52 Week Range', '107.32 - 157.26'), ('Market Cap', '$2.37T'), ('Shares Outstanding', '17.34B'), ('Public Float', '16.51B'), ('Beta', '1.20'), ('Rev. per Employee', '$1.865M'), ('P/E Ratio', '27.99'), ('EPS', '$5.11'), ('Yield', '0.62%'), ('Dividend', '$0.22'), ('Ex-Dividend Date', 'Aug 6, 2021'), ('Short Interest', '100.93M'), ('% of Float Shorted', '0.61%'), ('Average Volume', '80.12M')]
```

In [ ]:
results_g = get_key_data("goog")

[('Open', '$2,798.12'), ('Day Range', '2,788.59 - 2,806.34'), ('52 Week Range', '1,489.45 - 2,936.41'), ('Market Cap', '$1.86T'), ('Shares Outstanding', '320.17M'), ('Public Float', '279.85M'), ('Beta', '1.08'), ('Rev. per Employee', '$1.348M'), ('P/E Ratio', '30.39'), ('EPS', '$92.24'), ('Yield', 'N/A'), ('Dividend', 'N/A'), ('Ex-Dividend Date', 'N/A'), ('Short Interest', '2.64M'), ('% of Float Shorted', '0.94%'), ('Average Volume', '1.05M')]


Expected Output
```
[('Open', '$2,798.12'), ('Day Range', '2,788.59 - 2,806.34'), ('52 Week Range', '1,489.45 - 2,936.41'), ('Market Cap', '$1.86T'), ('Shares Outstanding', '320.17M'), ('Public Float', '279.85M'), ('Beta', '1.08'), ('Rev. per Employee', '$1.348M'), ('P/E Ratio', '30.39'), ('EPS', '$92.24'), ('Yield', 'N/A'), ('Dividend', 'N/A'), ('Ex-Dividend Date', 'N/A'), ('Short Interest', '2.64M'), ('% of Float Shorted', '0.94%'), ('Average Volume', '1.05M')]
```

In [ ]:
results_m = get_key_data("msft")

[('Open', '$296.22'), ('Day Range', '293.76 - 296.64'), ('52 Week Range', '199.62 - 305.84'), ('Market Cap', '$2.22T'), ('Shares Outstanding', '7.51B'), ('Public Float', '7.4B'), ('Beta', '1.19'), ('Rev. per Employee', '$928.66K'), ('P/E Ratio', '36.60'), ('EPS', '$8.06'), ('Yield', '0.84%'), ('Dividend', '$0.62'), ('Ex-Dividend Date', 'Nov 17, 2021'), ('Short Interest', '44.2M'), ('% of Float Shorted', '0.60%'), ('Average Volume', '23.03M')]


Expected Output
```
[('Open', '$296.22'), ('Day Range', '293.76 - 296.64'), ('52 Week Range', '199.62 - 305.84'), ('Market Cap', '$2.22T'), ('Shares Outstanding', '7.51B'), ('Public Float', '7.4B'), ('Beta', '1.19'), ('Rev. per Employee', '$928.66K'), ('P/E Ratio', '36.60'), ('EPS', '$8.06'), ('Yield', '0.84%'), ('Dividend', '$0.62'), ('Ex-Dividend Date', 'Nov 17, 2021'), ('Short Interest', '44.2M'), ('% of Float Shorted', '0.60%'), ('Average Volume', '23.03M')]
```

Extra Tests

In [ ]:
results_m = get_key_data("pfe")

[('Open', '$42.73'), ('Day Range', '42.34 - 42.91'), ('52 Week Range', '32.78 - 51.86'), ('Market Cap', '$239.63B'), ('Shares Outstanding', 'N/A'), ('Public Float', '5.6B'), ('Beta', '0.67'), ('Rev. per Employee', '$533.86K'), ('P/E Ratio', '18.20'), ('EPS', '$2.34'), ('Yield', '3.67%'), ('Dividend', '$0.39'), ('Ex-Dividend Date', 'Nov 4, 2021'), ('Short Interest', '54.09M'), ('% of Float Shorted', '0.97%'), ('Average Volume', '32.61M')]


In [ ]:
results_m = get_key_data("mrna")

[('Open', '$310.80'), ('Day Range', '297.54 - 314.05'), ('52 Week Range', '65.49 - 497.49'), ('Market Cap', '$124.87B'), ('Shares Outstanding', '403.65M'), ('Public Float', '344.8M'), ('Beta', '0.28'), ('Rev. per Employee', '$618.00K'), ('P/E Ratio', '38.06'), ('EPS', '$8.01'), ('Yield', 'N/A'), ('Dividend', 'N/A'), ('Ex-Dividend Date', 'N/A'), ('Short Interest', '14.3M'), ('% of Float Shorted', '4.15%'), ('Average Volume', '19.35M')]


In [ ]:
results_m = get_key_data("jnj")

[('Open', '$161.32'), ('Day Range', '160.25 - 161.61'), ('52 Week Range', '133.65 - 179.92'), ('Market Cap', '$424.72B'), ('Shares Outstanding', '2.63B'), ('Public Float', '2.63B'), ('Beta', '0.64'), ('Rev. per Employee', '$613.92K'), ('P/E Ratio', '24.20'), ('EPS', '$6.65'), ('Yield', '2.63%'), ('Dividend', '$1.06'), ('Ex-Dividend Date', 'Aug 23, 2021'), ('Short Interest', '17.27M'), ('% of Float Shorted', '0.66%'), ('Average Volume', '5.88M')]
